<a href="https://colab.research.google.com/github/angelgold1004/stock_market_analysis/blob/main/230405_%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4_numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 과제 1
## Q1. 


<div class="alert alert-success">
[문제1]     
    
원소가 1부터 5까지인 배열 arr이 있다. 각각의 요소의 루트를 씌운 값의 총합을 구하시오. 
</div>

------------
[힌트]  
np.arange(1, 6)  
list = [1,2,3,4,5]   
8.382332347441762  

In [ ]:
import numpy as np

# 원소가 1부터 5까지인 배열 arr 생성
arr = np.array([1,2,3,4,5])
# arr = np.arange(1, 6)

# 루트: sqrt, 총합: sum
np.sum(np.sqrt(arr))

8.382332347441762

## Q2. 

<div class="alert alert-success">
[문제2]
    
    
다음과 같은 배열 arr2를 만드시오.  
    
    
arr2 = ( arr의 총합, arr의 평균, arr의 최소값, arr의 최대값)  
[15.  3.  1.  5.]  
</div>

In [ ]:
# 총합: sum, 평균: mean, 최소값: min, 최대값: max
arr2 = np.array([np.sum(arr), np.mean(arr), np.min(arr), np.max(arr)])
arr2

array([15.,  3.,  1.,  5.])

## Q3.

<div class="alert alert-success">
[문제3]
    
    
arr2의 구조를 확인하고(shape),
arr2를 전치(transpose)한 배열 arr3를 만드시오.
</div>

------------
[힌트]  

arr3의 출력 결과

[[15.]  
 [ 3.]   
 [ 1.]  
 [ 5.]]

In [ ]:
# arr2의 구조를 확인
arr2.shape

(4,)

In [ ]:
arr2

array([15.,  3.,  1.,  5.])

In [ ]:
# 1차원 배열의 경우, 전치(transpose)한 결과가 동일
arr2.T

array([15.,  3.,  1.,  5.])

In [ ]:
# 1차원 배열을 2차원으로 변경(reshape)
# 방법1
arr2.reshape((1,4)).T

# 방법2
arr2.reshape(4,1)

array([[15.],
       [ 3.],
       [ 1.],
       [ 5.]])

In [ ]:
arr3 = arr2.reshape((1,4)).T


## Q4. 


<div class="alert alert-success">
[문제4]
    
    
arr2와 arr3를 행렬 곱 연산한 결과 값은 ? 
</div>

[힌트]


 260.
 
 
 또는
 
 
 
 [[225.  45.  15.  75.]  
 [ 45.   9.   3.  15.]   
 [ 15.   3.   1.   5.]   
 [ 75.  15.   5.  25.]]   




In [ ]:
arr2.dot(arr3)

array([260.])

In [ ]:
print(arr2.shape)
print(arr3.shape)

(4,)
(4, 1)


In [ ]:
arr3.dot(arr2.reshape(1,4))

array([[225.,  45.,  15.,  75.],
       [ 45.,   9.,   3.,  15.],
       [ 15.,   3.,   1.,   5.],
       [ 75.,  15.,   5.,  25.]])

# 과제 2
## Q5.


<div class="alert alert-success">
[문제5]
    
    
arange 함수를 이용하여 원소가 1부터 16까지인 배열 arr을 만드세요.
</div>


In [ ]:
arr = np.arange(1, 17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Q6. 


<div class="alert alert-success">
[문제6]
    
    
arr 배열을 4행 4열로 형상 변경하세요.
</div>


In [ ]:
# reshape
arr = arr.reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Q7. 


<div class="alert alert-success">
[문제7]
    
arr에 대해 인덱싱과 슬라이싱을 이용하여 다음과 같은 배열 arr2, arr3를 만드시오.  
arr2 :   
 [[2 3 4]  
 [6 7 8]]

arr3 :   
 [[5 6 7]]  
</div>




In [ ]:
arr2 = arr[0:2, 1:4]
arr2

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
arr3 = arr[1, 0:3]
arr3

array([5, 6, 7])

## Q8.

<div class="alert alert-success">
[문제8]
    
arr3를 전치(transpose)하세요.
</div>

-----------------
[힌트]


[[5]  
 [6]  
 [7]]  


In [ ]:
arr3 = arr3.reshape(1,3).T

## Q9.


<div class="alert alert-success">
[문제9]
    
arr2와 arr3를 행렬 연산한 결과를 구하시오.
</div>

-----------------




**[결과]**  
[[ 56]  
 [128]]

In [ ]:
# print(arr2.shape)
# print(arr3.shape)
arr2.dot(arr3)

array([[ 56],
       [128]])

# 과제 3
## Q10.

<div class="alert alert-success">
[문제10]
    
np.random을 이용하여 모든 요소의 값이 3 <= 값 < 7인   
요소 4개를 갖는 1차원 배열 arr을 생성하시오.  
예시) arr = [4, 3, 4, 6]  
</div>





In [ ]:
arr = np.random.randint(3, 7, 4)
arr

array([6, 4, 6, 3])

In [ ]:
import numpy as np
arr = np.random.randint(3, 7, 4)
arr

array([4, 5, 5, 4])

## Q11. 

<div class="alert alert-success">
[문제11]
    
arr을 2*2 형상 변경하시오.
</div>


In [ ]:
arr.reshape(2,2)

array([[4, 5],
       [5, 4]])

## Q12. 


<div class="alert alert-success">
[문제12]
다음과 같이 동작하는 로또 번호 생성기를 작성하시오.
    
    
    - 사용자로부터 로또 번호를 몇 개 생성할지 입력받는다    
    
    - 사용자가 입력한 개수 만큼 로또 번호를 생성하여 출력한다    
    
    - 로또번호는 숫자가 작은 수부터 순서대로 정렬하여 출력한다
    
    - 로또 번호는 1부터 46까지 서로 다른 6개의 정수로 이루어져있다    
        
    - 로또 번호 생성기 로직은 함수로 작성하여 재활용이 가능하도록 한다    
   

</div>
    
[실행 예시]
로또번호를 몇 개 생성할까요? 3  
1. 로또번호: [10 13 16 30 37 41]  
2. 로또번호: [ 4 10 15 25 29 42]  
3. 로또번호: [ 6 26 31 39 40 45]  

  

In [ ]:
n = input('로또번호를 몇 개 생성할까요? ')
for i in range(int(n)):
    lotto = np.random.randint(1, 47, 6)
    print('{}. 로또번호:{}'.format(str(i+1), np.sort(lotto)))

로또번호를 몇 개 생성할까요? 3
1. 로또번호:[ 4  5 17 18 21 34]
2. 로또번호:[12 19 19 26 27 33]
3. 로또번호:[ 2 14 17 19 27 40]


## Q13. 


<div class="alert alert-success">
    
[문제13]
    
오늘의 로또번호는 [9, 12, 17, 21, 40, 42]입니다.  
    
오늘의 로또번호 합보다 더 큰 조합을 가지고 있는 경우, 이벤트 쿠폰을 발행하려고 합니다.
    
몇 장의 이벤트 쿠폰을 발행해야하는지 판단하는 로직을 작성하세요

</div>

[실행 예시]



로또번호를 몇 개 생성할까요? 3
1. 로또번호: [ 1 15 36 39 41 45]  
이벤트 당첨, 오늘의 로또번호 합= 141, 당첨된 로또번호 합=177
2. 로또번호: [ 6  9 12 19 27 42]  
3. 로또번호: [ 4  7 36 39 39 44]  
이벤트 당첨, 오늘의 로또번호 합= 141, 당첨된 로또번호 합=169


In [ ]:
today = np.array([9, 12, 17, 21, 40, 42])

def createLottoNumber2(count):
    for i in range(int(n)):
        lotto = np.random.randint(1, 47, 6)
        print('{}. 로또번호:{}'.format(str(i+1), np.sort(lotto)))
        print('   이벤트 당첨, 오늘의 로또번호 합= {}, 당첨된 로또번호 합={}'.format(today.sum(), lotto.sum()))
        
count = int(input("로또번호를 몇 개 생성할까요? "))
createLottoNumber2(count)

로또번호를 몇 개 생성할까요? 3
1. 로또번호:[18 22 28 33 40 43]
   이벤트 당첨, 오늘의 로또번호 합= 141, 당첨된 로또번호 합=184
2. 로또번호:[ 4  5 14 21 33 42]
   이벤트 당첨, 오늘의 로또번호 합= 141, 당첨된 로또번호 합=119
3. 로또번호:[ 2 10 17 21 38 41]
   이벤트 당첨, 오늘의 로또번호 합= 141, 당첨된 로또번호 합=129


# 과제 4
## Q14. 


<div class="alert alert-success">
    
[문제14]
    
수학 시험 답안 채점 프로그램을 만드시오.
    
    정답 = [3, 2, 1, 4, 4, 3, 4, 4, 3, 3]
    
    - 문제 수: 10
    - 보기: 1번 ~ 5번
    - 학생들의 샘플 답안 생성: 10개
    - 문항 별 정오답 여부 출력
    - 10점 만점에 몇 점인지 출력
</div>


1. 채점결과: [False  True False False  True False False False  True  True], 점수: 4
2. 채점결과: [False  True False  True False False False  True False False], 점수: 3
3. 채점결과: [ True  True  True False False False False  True False  True], 점수: 5
4. 채점결과: [False False  True False False  True False False False  True], 점수: 3
5. 채점결과: [False  True False  True False  True False  True False False], 점수: 4
6. 채점결과: [False False False  True False False False False False False], 점수: 1
7. 채점결과: [False  True  True False  True False False False False  True], 점수: 4
8. 채점결과: [False  True  True False False False  True False False False], 점수: 3
9. 채점결과: [ True False False False False  True False  True False False], 점수: 3
10. 채점결과: [False  True  True False False False  True False False False], 점수: 3


In [ ]:
# 주어진 코드
correct = np.array([3, 2, 1, 4, 4, 3, 4, 4, 3, 3])

count = 10
students = 10
answers = np.random.randint(1, 5, size=count*students)
answers = answers.reshape(count, students)

In [ ]:
def check_answer_sheet(correct, answers):
    for i in range(students):
        check = np.array(correct == answers[i])
        print("{}. 채점결과:{}, 점수:{}".format(i+1, check, np.sum(check)))

check_answer_sheet(correct, answers)

1. 채점결과:[False  True False False False False False False False False], 점수:1
2. 채점결과:[False False False False False  True False  True  True False], 점수:3
3. 채점결과:[ True False False False False  True False  True False  True], 점수:4
4. 채점결과:[False False False False  True False False False  True False], 점수:2
5. 채점결과:[ True False False False False False False False False False], 점수:1
6. 채점결과:[False  True  True False False False  True False False False], 점수:3
7. 채점결과:[False False False False False  True False False False  True], 점수:2
8. 채점결과:[False False False  True False  True  True  True False  True], 점수:5
9. 채점결과:[False False  True  True False  True  True  True False  True], 점수:6
10. 채점결과:[False  True False False False False False False False  True], 점수:2
